### ISSUE TITLE
Ask about the implementation of the API load method

### ISSUE THREAD

**Issue by oularrea** [ImperialCollegeLondon/django-drf-filepond#2]
Hello, I'm using this component to change the profile picture of the user, and I'm encountering problems when initializing the component with the saved image, since the load method is not implemented and it is not clear to me that I return in the API to see the preview of the profile image previously saved.

Do you have any examples of the implementation of the load method? passing the upload_id of the TemporaryUpload model as a parameter

Thank you

![image](https://user-images.githubusercontent.com/15090002/51433015-e875d880-1c41-11e9-8162-4afb99afcb46.png)

add init files
![image](https://user-images.githubusercontent.com/15090002/51433023-03484d00-1c42-11e9-804a-460e20e3481c.png)

**Comment by jcohen02** [comment]
HI @oularrea, thanks for raising this issue. It's correct that the load method is not yet implemented. I hadn't had a chance to add support for this yet and wasn't sure of example use cases for this. As such, implementation of the `process`, `revert` and `fetch` endpoints was prioritised.

I'll look to get support for `restore` and `load` added as soon as possible - hopefully this will be available within the next few days.

I don't have any examples of this yet and was hoping to look into the correct intended use of `restore` and `load` since I'm a little unsure of the difference based on the description in the filepond [server API](https://pqina.nl/filepond/docs/patterns/api/server/#restore) documentation.

**Comment by oularrea** [comment]
Thank you for answering so quickly

In my case I use it to load the profile picture and when I initialize according to the upload_id code, this makes a call to the load method of the api, like I think that if you have a multiple upload of files this method is also important, since It would be a little weird to have a component to view the saved files or images and then use the Filepond just to upload files.

I think this would be the most common use for this load method, to initialize the component

Thank you very much I hope the update

**Comment by jcohen02** [comment]
No problem, thanks for the info on your use case.

For the `restore` endpoint, the handling of requests is straightforward since the file associated with the requested ID will still be in the django-drf-filepond [TemporaryUpload](https://github.com/ImperialCollegeLondon/django-drf-filepond/blob/87004f5e5ba0623171b7f35850d765714d035355/django_drf_filepond/models.py#L22) table.

The decision made in terms of handling stored files was that developers of applications using django_drf_filepond would probably want to handle the files themselves once it is determined that the upload is to be stored permanently. This is the approach described in the "[Working with file uploads](https://django-drf-filepond.readthedocs.io/en/latest/#working-with-file-uploads)" section in the docs.

It sounds like an alternative approach where django-drf-filepond has some more control over the permanent storage of the files is required, at least to enable the `load` endpoint to be supported. (This will be optional and the existing approach will remain unaffected.)

When a call is made to the `load` endpoint of django-drf-filepond, it is passed an ID that represents a permanently stored file. To address this, I think a lightweight approach will be to add an (optional) setting to the app where you can specify your permanent file storage location that your application uses. A `store` function in the server-side API for django-drf-filepond will enable you to easily store a file represented by a `TemporaryUpload` record to this location once you know it needs to be permanently stored. It can then be subsequently looked up there by a `load` request. This will avoid the need for another database table that keeps track of stored uploads which I think is preferable if the main application is already handling this. However, it could be added if there are use cases for this approach.

**Comment by jcohen02** [comment]
@oularrea, this is still a work in progress but there's now a prototype implementation for the `restore` and `load` methods in the branch [feature/restore_load](https://github.com/ImperialCollegeLondon/django-drf-filepond/tree/feature/restore_load) if you'd like to try it out and see if provides what you were looking for.

The configuration requires that you add a setting `DJANGO_DRF_FILEPOND_FILE_STORE_PATH` into your django application settings. This should point to the absolute path on the filesystem where stored files will be loaded from. Within that directory, you should store files in directories named using the 22-character unique IDs provided by django-drf-filepond when you make an upload. Each of these directories should contain a single file _named with it's original name, not a 22-character ID_.

e.g. If you set `DJANGO_DRF_FILEPOND_FILE_STORE_PATH = '/tmp/data_files'`, you can then place your permanently stored uploads within directories under this directory. So, if you have a file _some-image.png_, that was assigned the upload id `bcdefgbcdefgbcdefgbcde`, making a request to the endpoint `/fp/load/?name=bcdefgbcdefgbcdefgbcde` will attempt to return the file `/tmp/data_files/bcdefgbcdefgbcdefgbcde/some_image.png`.

This current setup is similar to the approach used in the [filepond-boilerplate-php](https://github.com/pqina/filepond-boilerplate-php) repository.

I'm still considering whether it would be better for django-drf-filepond to maintain a StoredFiles table containing additional file information. This would remove the need for files to be stored in a specific layout/structure and would also allow storing of the MIME type - at present this is guessed based on the file extension using the Python [mimetypes](https://docs.python.org/3/library/mimetypes.html) module but this could be significantly improved by either storing the MIME type used when the file was uploaded (if the database storage approach is used), or using something like [python-magic](https://github.com/ahupp/python-magic) to determine the file type, but this adds an additional dependency and I think it may also present some compatibility issues with different platforms.

**Comment by jcohen02** [comment]
This feature is now available in [release v0.0.5](https://github.com/ImperialCollegeLondon/django-drf-filepond/releases/tag/v0.0.5).
