### ISSUE TITLE
DRF Authentication

### ISSUE THREAD

**Issue by pasevin** [ImperialCollegeLondon/django-drf-filepond#20]
Is it possible to prevent file uploads without access token?
Right now it looks like I can upload files without authenticating.
Looks like a potential vulnerability :)

**Comment by jcohen02** [comment]
You're right that there was no work done on authentication here as yet.

Thanks very much for the PR @pasevin, I'll take a look through this in the next few days.

**Comment by jcohen02** [comment]
Apologies, I rebased your PR onto the new release that I just made (v0.2.2) with the fix for issue 18. I wanted to retain your original PR so (force) pushed back to your fork (which I didn't think it would let me do!) but it did and seems to have lost the PR in the process...sorry.

If you could recreate the PR, that would be great, your master should now contain your authentication changes rebased on top of the merge for issue 18 as well as a tidy up of the imports and a couple of PEP8 fixes to the code. Thanks.

**Comment by pasevin** [comment]
I think i sorted it out :] https://github.com/ImperialCollegeLondon/django-drf-filepond/pull/24

**Comment by jcohen02** [comment]
Added in PR #24. Many thanks @pasevin.
