### ISSUE TITLE
I don't think delete_temp_upload_file is a good Idea

### ISSUE THREAD

**Issue by danidee10** [ImperialCollegeLondon/django-drf-filepond#3]
First of all, Great library. It saved me from writing a `filepond` server but I have a problem with how it works.

Going through the code, I saw that there's a signal called `delete_temp_upload_file` that deletes the Temporary directory whenever an file is deleted.
I don't think this is a good Idea because It seems wastefu.

There's no point deleting the directory, when the next file upload will recreate it.
When there's a lot of concurrent image requests and you have multiple processes/threads deleting and recreating the directory, The OS has to do a lot of work to keep everything in sync which could cause degraded performance (and possibly corrupt data?)

I suggest that you disable this behaviour by default and make it optional. `.delete` should only delete the temporary files not the temporary directory.
Developers can easily write a cron or `celery` task to clean the temporary directory periodically.

In my case, there's no need to call `.delete` because I use `Docker`.
The temporary directory is cleared everytime I restart the container.

**Comment by jcohen02** [comment]
Hi @danidee10, thanks for raising this. I take your point on the overhead of creating/removing lots of directories if you're handling a large number of concurrent uploads in multiple threads/processes.

The implementation was handled in this way in order to follow the approach described in the filepond spec/docs for the [server-side of the process method](https://pqina.nl/filepond/docs/patterns/api/server/#process) where it describes using a uniquely named directory in which to store each uploaded file. I'm assuming this is in order to avoid filename clashes since the uploaded file seems to be stored with it's original name according to the docs. I slightly changed this to use a unique ID for the filename too, storing the actual filename in the database in order to avoid any filesystem-specific naming issues. Nonetheless, the directory in which the upload is stored only applies to that specific upload so once the temporary upload is deleted, the directory is redundant.

You said "There's no point deleting the directory, when the next file upload will recreate it.". Apologies if I've misunderstood your point here but just to clarify, the top-level upload directory (the one specified by the `DJANGO_DRF_FILEPOND_UPLOAD_TMP` setting) is not deleted, only the temporary directory that a specific upload was stored in. That directory will not be re-created by a subsequent upload (although a different one named with another unique name will).

I can see that this provides unnecessary overhead. Indeed, the very early prototype just pooled all uploads in a single temporary directory using a unique name for each file. In hindsight, maybe this is a better approach but it was changed to stay inline with the filepond documentation. The intention here was to ensure that the library doesn't leave lots of empty directories floating around in the temporary upload directory.

Happy to add a feature that you can switch on to disable the removal of temporary directories created in the upload directory if that would be useful to you. There will, of course, still be a temporary directory created for each upload so maybe a more fundamental approach to the way file storage is handled is necessary...

**Comment by jcohen02** [comment]
Just merged an update into master to address this - not sure how well this addresses what you were looking for, @danidee10, but you can now set `DJANGO_DRF_FILEPOND_DELETE_UPLOAD_TMP_DIRS = False` to prevent the temporary directory associated with an upload from being deleted when the temporary file is deleted. I plan to include this in the next release if it is helpful. As you highlighted in your original message, you'll probably need some sort of independent process to clean up temporary directories when using this feature.

**Comment by danidee10** [comment]
Thanks for the quick response!

Concerning this statement:

_**"There's no point deleting the directory, when the next file upload will recreate it.".**_

I was wrong, I thought the top-level directory was being deleted, but it seems that's not the case.
If it's only temporary sub-directories that are deleted, I don't think it's a big problem because two processes can write to the same directory without any OS locks. But I'm glad that you added a feature to disable it though. Thanks! :+1: (It'll potentially save a lot of `Bytes`)

I also think it's better to follow the `filepond` documentation (I didn't know that there was a documentation for the server Implementation). They mentioned something about `chunk-uploading` which probably depends on having the same directory structure.

It's also best to follow the documentation so you don't surprise others with a custom behaviour that's different from the recommended one.

**Comment by jcohen02** [comment]
Thanks, I'll leave the feature in place and add details of the new configuration option to the documentation.
