### ISSUE TITLE
Bug: Error when using custom the user model

### ISSUE THREAD

**Issue by clikader** [ImperialCollegeLondon/django-drf-filepond#38]
The models.py have two locations where the foreign key to users are defined by `auth.User`, if the project is using the custom user model, the following errors will be given:

```
ERRORS:
django_drf_filepond.StoredUpload.uploaded_by: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.
	HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.
django_drf_filepond.TemporaryUpload.uploaded_by: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.
	HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.
```

Using `settings.AUTH_USER_MODEL` solved the problem and according to [the documentation](https://docs.djangoproject.com/en/3.0/ref/settings/#auth-user-model), `AUTH_USER_MODEL` by default gives `auth.User`.

**Comment by iver56** [comment]
Workaround, until the bug gets fixed: Use v0.2.2, where this problem doesn't exist

**Comment by jcohen02** [comment]
Thanks for highlighting this issue @iver56 and reporting that this doesn't exist in `v0.2.2`. I guess this must have been introduced by the most recent changes to try and address #31. I've tried simply switching the `User` foreign keys to `AUTH_USER_MODEL` but the test suite is reporting failures so I still need to investigate this.

**Comment by michealjroberts** [comment]
@jcohen02 However, when downgrading - ERROR: django-drf-filepond 0.2.2 has requirement Django<3.0.0; python_version >= "3.5", but you'll have django 3.0.2 which is incompatible. I believe I can help with this issue...it shouldn't be too much of an issue to resolve.

**Comment by jcohen02** [comment]
Hi @michealjroberts, if you'd like to fix this and put in a PR, please do go ahead. Thanks.

**Comment by jcohen02** [comment]
@michealjroberts I've just pushed an update to the [fix/issue38](https://github.com/ImperialCollegeLondon/django-drf-filepond/tree/fix/issue38) branch to address the original issue raised by @clikader.

Is the versioning issue still causing a problem? If so, can you provide some further details about the circumstances in which this occurs?

When I attempt a downgrade using `pip`, e.g. `pip install django-drf-filepond==v0.2.2`, while I have a newer version (and Django 3) currently installed, I see it remove Django 3 and install Django 2.2.12 as well as django-drf-filepond 0.2.2. When I then upgrade to the latest version again (e.g. `pip install --upgrade django-drf-filepond`) I see Django 2.2.12 removed and 3 installed. This is the behaviour I would expect.

If there's an issue to fix here, I can try and do that and add it to #39 which can then be merged into `dev`.

Thanks.

**Comment by iver56** [comment]
The fix in [fix/issue38](https://github.com/ImperialCollegeLondon/django-drf-filepond/tree/fix/issue38) seems to do the trick for me 👍 Thanks

Btw, since you asked about versioning issues:
I had a similar issue. I am using Django LTS (currently 2.2), in a Python 3.7 environment. My solution was to tweak setup.py to indicate that this combination is supported/allowed, like this: https://github.com/iver56/django-drf-filepond/commit/0380bbaef241d5c3eec81843b1bbbaef20943adf

**Comment by jcohen02** [comment]
Re versioning issues, thanks for the pointer to your changes, @iver56. I can see that this will allow you to run Django 2.2 with Python 3.7 but I _think_ that I had an issue where if you did a fresh install with, say, Python 3.5, it would still install Django 3 which is not supported by 3.5. 

I think this was the reason for the somewhat complex set of rules for Django versions in `setup.py`. I may be wrong so will check this out. 

If that's the case, maybe just changing `"Django>=3.0.2;python_version>='3.6'"` to `"Django>=2.2;python_version>='3.6'"` will solve the problem? This should ensure that installing with versions of Python <= 3.5 doesn't result in Django 3+ being installed and that Python 3.6+ will work with 2.2LTS or newer (since 1.11LTS is now just out of extended support anyway).

**Comment by iver56** [comment]
Yes, that sounds like an apt fix 👍

**Comment by jcohen02** [comment]
Fixes merged into [dev](https://github.com/ImperialCollegeLondon/django-drf-filepond/tree/dev) in #39
