### ISSUE TITLE
Model Form validation with FilePond form.save()

### ISSUE THREAD

**Issue by shafay07** [ImperialCollegeLondon/django-drf-filepond#50]
Firstly, thankyou for developing django-drf-filepond. Its a life saver!
I am a lil confused as to how django-drf-filepond helps with form validation on post request. So i have set up everything and my files are uploaded to temporary folder. I want to know if my post request validation (that is form.save()) fails how do i keep track of uploaded files and let user fix errors with the parent form.

**Comment by jcohen02** [comment]
Hi @shafay07, great that you're finding the app useful and apologies for the slightly slow response.
If I understand your question correctly, you have a form that includes file upload capability via filepond, so when someone adds a file, it gets uploaded straight away, as a temporary upload, and then subsequently a user submits the main form which is handled on the server-side as a `ModelForm` instance? If the saving of the `ModelForm` instance fails due to, for example, a validation error, you want to return the previously submitted form content back to the client along with error details but also keep track of the temporary upload ID?

`django-drf-filepond` doesn't directly provide any support for this since it's intended to operate independently of how you submit/handle/process the form in your application. However, even if you don't have an entry in the underlying model for your temporary upload ID (which you probably don't want to store), this shouldn't be too much trouble to handle.

When `django-drf-filepond` uploads an added file, you get a temporary upload ID back if the upload was successful - presumably you store this somewhere in your page, e.g. in a hidden field in your form? I'm assuming you need to submit the temporary upload ID with your form so that you can tie the upload(s) to the form submission and then store the upload(s) if the form submission is successful? In this case, if you're submitting the temporary upload ID with your form content, but it's not included in the underlying model that the `ModelForm` is attached to, you should be able to extract the upload ID from the form content in the request when it's received on the server side, validate your form, and then insert the upload ID back into the form data in the response before returning it to the client. Assuming you then use this content on the client side to re-render your form, and you have a hidden form field for the temporary upload ID, I think this should work fine.

Hope that makes sense and I've correctly understood your question but let me know if not, or if you require further information.

**Comment by jcohen02** [comment]
@shafay07 - I hope the above response answered your question, I'm going to close this issue now since there's been no further discussion, however, you're welcome to re-open the issue if you have further questions or suggestions on this. Thanks.

**Comment by shafay07** [comment]
@jcohen02 Hi, i hope you're doing great. Firstly apologies for a late comment and thank you for a detailed answer. Yes i ended up adding file id's to the post request and used filepond init method to add those files as follow:

views.py
`
temp_uploaded_files = request.POST.getlist('filepond')
context = {
        'form': offerForm,
        'temp_uploaded_files': temp_uploaded_files
    }
`

html template:
`
{% if temp_uploaded_files  %}
    const pond = FilePond.create(inputElement, {
        acceptedFileTypes: ['image/*'],
        files: [
        {% for file in temp_uploaded_files %}
        {
            // the server file reference
            source: '{{file}}',

            // set type to limbo to tell FilePond this is a temp file
            options: {
                type: 'limbo'
            }
        },
        {% endfor %}
        ]
    });
    {% else %}
    const pond = FilePond.create(inputElement, {
        acceptedFileTypes: ['image/*'],
        labelIdle : 'Drag & Drop product images or <span class="filepond--label-action"> Browse </span>'
    });
    {% endif %}
` 

Also i disable the submit button for the form using the following js whenever user is uploading a file:
`
pond.onaddfilestart = function(file){
        let submitBtn = $('#submitForm');
        if (pond.status != 4){
            submitBtn.attr("disabled", true);
            submitBtn.html('<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> Uploading images...');

        }

    };
`
