### ISSUE TITLE
Template Tags for easy front end implementation

### ISSUE THREAD

**Issue by derek-adair** [ImperialCollegeLondon/django-drf-filepond#61]
perhaps it's out of the scope of this project, but it'd be convenient to have some template tags baked in and maybe even a specific version of filepond.  I can picture some kind of ModelForm integration as well where I am able to declare a form as a DRFFilepondForm or something.

**Comment by jcohen02** [comment]
Hi @derek-adair, thanks for the suggestion. Are you thinking to include, for example, a template tag that drops in the script tag to load the latest (or a specific) version of filepond for use in apps working with server-side rendering? I can also see that a tag could be included to drop a filepond form into a template and, as you suggest, some sort of form object to handle submission on the server side.

So far, _django-drf-filepond_ has focused on providing an independent backend for the filepond client. I can see that the sort of additional support you suggest could be useful for developers building applications that focus on server-side rendering from django templates. At one level, this is out of scope given the original aims of _django-drf-filepond_. However, since I'm assuming that adding this support could be achieved without affecting the existing functionality of the library, I'd be happy to consider this as a potentially useful addition.

**Comment by derek-adair** [comment]
> Hi @derek-adair, thanks for the suggestion. Are you thinking to include, for example, a template tag that drops in the script tag to load the latest (or a specific) version of filepond for use in apps working with server-side rendering? 
Maybe, I was mainly thinking of just packaging the specific version because it would likely break the template tag if a user didn't have the right version.  I think this would just work best by adding the necessary src to the base filepond template.

>I can also see that a tag could be included to drop a default filepond form into a template and, as you suggest, some sort of form object to handle submission on the server-side.

This would be the main bit, but after I spent a little time thinking about it I think it's best to keep the distinct concern of having this be exclusively the backend.  I think the same thing could be achieved by some complete demos of some more advanced implementations.

I'll be closing this and submitting a docker based example that takes your tutorial a step further by showing how to work with the uploads in a django app.  It was a bit hard for me to wrap my head around how filepond really works and what needed to be done beyond the server side implementation within the context of django.
