### ISSUE TITLE
save image to ImageField

### ISSUE THREAD

**Issue by darbre** [ImperialCollegeLondon/django-drf-filepond#78]
Hi
I use FilePond Vue.js +  django-drf-firepond. I want to save images in ImageField. I am sending a request with upload_id via axios. But nothing works. How to implement it?
Here is part of the code views.py.
Thank You
```
@api_view(['PATCH'])
def change_instance(request, instanceID):
        instance = generics.get_object_or_404(Instance, id=instanceID)
        avatar_uploudID = request.data.get('avatar')

        if avatar_uploudID and avatar_uploudID != None:
            try:
                tu = TemporaryUpload.objects.get(upload_id=avatar_uploudID)
            except TemporaryUpload.DoesNotExist:
                raise Response("The specified file does not exist.", status=status.HTTP_404_NOT_FOUND
            avatar_path = 'user_{0}/'.format(request.user.id)+tu.upload_name
            su = store_upload(avatar_uploudID,avatar_path)
            my_avatar_image= open(os.path.join(settings.MEDIA_ROOT,avatar_path))
            myfile = File(my_avatar_image)
            request.data['avatar'] = myfile

        serializer =InstanceSerializer(instance,data=request.data, partial=True)

    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data, status=status.HTTP_200_OK)

    return Response(serializer._errors, status=status.HTTP_400_BAD_REQUEST)

```

**Comment by darbre** [comment]
Yes, i have a front end where a user selects an image file on their system which is successfully uploaded and saved on the server. I have the frontend client configured correctly (hopefully). 

Yes, i'm handling the request with the change_instance function.

Yes, the temporary upload stored on the server.

**Comment by darbre** [comment]
Hi!
Do you have any ideas how to save the image in ImageField?

Now I'm moving the image to the main folder `store_upload(avatar_uploudID,avatar_path)` and additionally changing the value in the object itself:
```
instance.avatar = avatar_path
instance.save()
```

But I don't think this is a good and universal solution. I will have several such ImageFields.

**Comment by darbre** [comment]
I thought _django-drf-filepond_, in addition to temporary loading on the server, could save a file in the Django field.
Yes, the images are uploaded to the server successfully, but how to save them in the field and, accordingly, in the database?

I only use Django field: models.ImageField.

**Comment by jcohen02** [comment]
Hi @darbre, thanks for providing this example code.

It's my understanding that the issue you are experiencing is not directly related to django-drf-filepond, it's an issue with how django rest framework is being used to handle image uploads. django-drf-filepond is correctly uploading the data and then you are correctly using the api function `store_upload` to store the temporary upload to a file.

With rest_framework's `ImageField` my understanding is that you'd normally use this in a view that directly receives the raw uploaded file data from the client. In your case, uploading the file data with django-drf-filepond bypasses the intended workflow of using `ImageField`. As such, I'm not sure that trying to connect up an `ImageField` within a serialiser after you've already uploaded and stored the data using the approach shown in your example `views.py` above is the optimal approach.

I've spent a significant amount of time trying to convert your example code above into a working example so I can try and demonstrate an alternative approach but I've not worked with vue.js and the code is missing imports and, for the client side, the structure and loading of dependency scripts to make this deployable as a single HTML file so that I can use it as a test client. Due to other commitments, I'm unfortunately unable to spend any more time on this at present.

If you're able to provide a simple, working, standalone example of what you're trying to do, for example something that can be cloned from a test repository and run, then I'm happy to try and offer some further assistance.

At this stage, my recommendation would be that you use the `store_upload` function, as you're already doing, to store the uploaded file data to the location set as `upload_to` in your `ImageField` definition in your `models.py`. Then, look at how the file link is stored in the database - I think it may just be a path to the stored file - then maybe you can update this directly. If you have a separate serialiser that you're using when accessing the data from the client, this should then still work.

I hope this helps and I'm sorry I'm not able to contribute any further time to trying to offer advice on this issue at present.

**Comment by derek-adair** [comment]
A couple things about this thread.  Honestly, @jcohen02 you are a saint for trying to help this individual, but this individual clearly does not understand this project nor how to wield django.  This entire thread is out of the scope of this project and for me... when people submit this stuff to my projects... I typically direct them to stack overflow and/or the documentation and immediately close the thread.

Anyways... If you are having issue's like this needs to look more closely at this project and recognize it's purpose... Which is to take filepond API requests and store and/or interact with them from filepond.

**This is not a one stop shop for file upload**.

In general, if you are having problems wielding this project I'd suggest you look more closely at how one might handle uploading images WITHOUT DRF-filepond.  It's almost no different.  Basically;

1. Do filepond file things in the front end.
2. Submit filepond form
3. Process the form in any of the numerous ways outlined in the documentation.
=====

@darbre I use something like this for my app:
 ```
       if avatar_uploudID and avatar_uploudID != None:
            avatar_path = 'user_{0}/'.format(request.user+avatar_uploudID)
            store_upload(avatar_uploudID,avatar_path)
            del request.data['avatar']
            instance.avatar = avatar_path
```
If this isn't working for you, i'd suggest you browse the django manual or some basic tutorials on how to wield django properly.

**Comment by jcohen02** [comment]
Just to close the discussion on this issue, I hope you managed to find a solution to your problem @darbre. As @derek-adair has pointed out, it looks like the issue that you're trying to solve is somewhat out of scope of the aims and design principles of _django-drf-filepond_ and that the problem you were facing is likely to be best handled using Django's built in file upload support or, indeed, other server-side libraries for handling uploads.

I appreciate that we all have to start somewhere with these tools and are often learning "on the job" as we go along. The tooling in the Python ecosystem is generally fantastic but depending on what technical background or prior experience people have, I also recognise that it can sometimes be really challenging to understand the models and approaches required to use these frameworks, especially if there aren't experienced colleagues or collaborators to ask for advice. On this basis, I tried to better understand the issue being reported here and to offer some thoughts and advice on how this could be addressed - I hope this was some help. 

More generally, I think it's really important that this remains an open, friendly and accessible open source project and from that perspective, I don't want to discourage the posting of issues such as this, it's great that the wider community finds this tool, wants to use it and engages with the project in the event of any questions or anything that isn't clear. I can't always guarantee that I'll have time to invest in digging in to such issues and trying to offer help but happy to try when possible.

Thanks @darbre and @derek-adair for your input on this issue, I'm going to close this now.
